"""empty message

Revision ID: 02c5686b5737
Revises: fa6ae5621ddb
Create Date: 2023-10-05 14:09:46.505686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c5686b5737'
down_revision = 'fa6ae5621ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('financial_goals', sa.String(length=255), nullable=True))
    op.add_column('customer', sa.Column('investment_style', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'investment_style')
    op.drop_column('customer', 'financial_goals')
    # ### end Alembic commands ###
