"""empty message

Revision ID: 14936d270ed1
Revises: 2ef7c6e311bf
Create Date: 2023-10-05 15:50:02.035350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14936d270ed1'
down_revision = '2ef7c6e311bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_profile', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('investment_profile_customer_id_fkey', 'investment_profile', type_='foreignkey')
    op.create_foreign_key(None, 'investment_profile', 'customer', ['user_id'], ['id'])
    op.drop_column('investment_profile', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_profile', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'investment_profile', type_='foreignkey')
    op.create_foreign_key('investment_profile_customer_id_fkey', 'investment_profile', 'customer', ['customer_id'], ['id'])
    op.drop_column('investment_profile', 'user_id')
    # ### end Alembic commands ###
