"""empty message

Revision ID: 1680a6eee987
Revises: 7b31db107729
Create Date: 2023-08-22 18:48:42.861303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1680a6eee987'
down_revision = '7b31db107729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_transaction', sa.Column('fees', sa.Float(), nullable=True))
    op.add_column('investment_transaction', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('investment_transaction', sa.Column('iso_currency_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_transaction', 'iso_currency_code')
    op.drop_column('investment_transaction', 'price')
    op.drop_column('investment_transaction', 'fees')
    # ### end Alembic commands ###
