"""empty message

Revision ID: 208cdb8759ac
Revises: 53081fc18133
Create Date: 2023-09-19 18:50:33.744327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208cdb8759ac'
down_revision = '53081fc18133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('plaid_access_token', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'bank_account', ['plaid_access_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bank_account', type_='unique')
    op.drop_column('bank_account', 'plaid_access_token')
    # ### end Alembic commands ###
