"""empty message

Revision ID: 292a27f1d7dc
Revises: 4d19715e95e2
Create Date: 2023-09-18 12:54:11.998005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '292a27f1d7dc'
down_revision = '4d19715e95e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_financial_data', sa.Column('sector', sa.String(length=50), nullable=False))
    op.add_column('stock_financial_data', sa.Column('trailing_pe_ratio', sa.Float(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('forward_pe_ratio', sa.Float(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('market_cap', sa.BigInteger(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('fifty_two_week_low', sa.Float(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('fifty_two_week_high', sa.Float(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('enterprise_to_revenue_ratio', sa.Float(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('enterprise_to_ebitda_ratio', sa.Float(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('net_income_margin', sa.BigInteger(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('total_revenue', sa.BigInteger(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('free_cash_flow', sa.BigInteger(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('earnings_growth', sa.Float(), nullable=True))
    op.add_column('stock_financial_data', sa.Column('revenue_growth', sa.Float(), nullable=True))
    op.drop_column('stock_financial_data', 'gross_profit')
    op.drop_column('stock_financial_data', 'net_revenue')
    op.drop_column('stock_financial_data', 'net_income')
    op.drop_column('stock_financial_data', 'operating_income')
    op.drop_column('stock_financial_data', 'eps')
    op.drop_column('stock_financial_data', 'number_shares')
    op.drop_column('stock_financial_data', 'net_margin')
    op.drop_column('stock_financial_data', 'total_dividends')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_financial_data', sa.Column('total_dividends', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_financial_data', sa.Column('net_margin', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_financial_data', sa.Column('number_shares', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('stock_financial_data', sa.Column('eps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('stock_financial_data', sa.Column('operating_income', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('stock_financial_data', sa.Column('net_income', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('stock_financial_data', sa.Column('net_revenue', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('stock_financial_data', sa.Column('gross_profit', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_column('stock_financial_data', 'revenue_growth')
    op.drop_column('stock_financial_data', 'earnings_growth')
    op.drop_column('stock_financial_data', 'free_cash_flow')
    op.drop_column('stock_financial_data', 'total_revenue')
    op.drop_column('stock_financial_data', 'net_income_margin')
    op.drop_column('stock_financial_data', 'enterprise_to_ebitda_ratio')
    op.drop_column('stock_financial_data', 'enterprise_to_revenue_ratio')
    op.drop_column('stock_financial_data', 'fifty_two_week_high')
    op.drop_column('stock_financial_data', 'fifty_two_week_low')
    op.drop_column('stock_financial_data', 'market_cap')
    op.drop_column('stock_financial_data', 'forward_pe_ratio')
    op.drop_column('stock_financial_data', 'trailing_pe_ratio')
    op.drop_column('stock_financial_data', 'sector')
    # ### end Alembic commands ###
