"""Added InvestmentProfile table

Revision ID: 2ef7c6e311bf
Revises: eb6ecbe9c8a4
Create Date: 2023-10-05 15:35:56.565961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ef7c6e311bf'
down_revision = 'eb6ecbe9c8a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('customer', 'investment_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('investment_profile', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_table('investment_profile')
    # ### end Alembic commands ###
