"""Adding db.BankAccount and InvestmentHolding

Revision ID: 405f57239599
Revises: 0015b0244067
Create Date: 2023-08-21 16:58:45.712481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405f57239599'
down_revision = '0015b0244067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('account_mask', sa.String(length=255), nullable=True),
    sa.Column('account_type', sa.String(length=255), nullable=True),
    sa.Column('account_subtype', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_holding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('security_id', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investment_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('security_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plaid_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=255), nullable=False),
    sa.Column('item_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('customer_email_key', 'customer', type_='unique')
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.create_unique_constraint('customer_email_key', 'customer', ['email'])
    op.drop_table('plaid_item')
    op.drop_table('investment_transaction')
    op.drop_table('investment_holding')
    op.drop_table('bank_account')
    # ### end Alembic commands ###
