"""empty message

Revision ID: 437214828993
Revises: 98371b6f65e9
Create Date: 2023-09-19 20:42:47.063358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437214828993'
down_revision = '98371b6f65e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plaid_item', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_item', 'last_updated')
    # ### end Alembic commands ###
