"""empty message

Revision ID: 4541c837ea58
Revises: 437214828993
Create Date: 2023-09-30 13:24:56.937434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4541c837ea58'
down_revision = '437214828993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('experience_level', sa.String(length=50), nullable=True))
    op.add_column('customer', sa.Column('current_investments', sa.String(length=250), nullable=True))
    op.add_column('customer', sa.Column('financial_goals', sa.String(length=250), nullable=True))
    op.add_column('customer', sa.Column('risk_tolerance', sa.String(length=50), nullable=True))
    op.add_column('customer', sa.Column('life_stage', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'life_stage')
    op.drop_column('customer', 'risk_tolerance')
    op.drop_column('customer', 'financial_goals')
    op.drop_column('customer', 'current_investments')
    op.drop_column('customer', 'experience_level')
    # ### end Alembic commands ###
