"""empty message

Revision ID: 47b525c0d3b3
Revises: 47a978f9e39d
Create Date: 2023-09-04 12:29:00.301361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b525c0d3b3'
down_revision = '47a978f9e39d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_view', sa.Column('type', sa.String(length=50), nullable=True))
    op.drop_column('investment_view', 'asset_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_view', sa.Column('asset_class', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('investment_view', 'type')
    # ### end Alembic commands ###
