"""empty message

Revision ID: 4d19715e95e2
Revises: 7b9c0631b714
Create Date: 2023-09-18 12:07:19.340125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d19715e95e2'
down_revision = '7b9c0631b714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_financial_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_symbol', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('stock_exchange', sa.String(length=50), nullable=False),
    sa.Column('total_dividends', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('net_revenue', sa.BigInteger(), nullable=True),
    sa.Column('gross_profit', sa.BigInteger(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('operating_income', sa.BigInteger(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('ebitda', sa.BigInteger(), nullable=True),
    sa.Column('ebitda_margin', sa.Float(), nullable=True),
    sa.Column('net_income', sa.BigInteger(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('number_shares', sa.BigInteger(), nullable=True),
    sa.Column('return_on_equity', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_symbol')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock_financial_data')
    # ### end Alembic commands ###
