"""empty message

Revision ID: 53081fc18133
Revises: 6e2b85116e69
Create Date: 2023-09-19 13:07:20.607697

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '53081fc18133'
down_revision = '6e2b85116e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('customer', 
                  sa.Column('created_at', 
                            sa.DateTime, 
                            nullable=False, 
                            server_default=text('CURRENT_TIMESTAMP'))
                  )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'created_at')
    # ### end Alembic commands ###
