"""empty message

Revision ID: 55bbc40d15f7
Revises: c06f656a02ff
Create Date: 2023-08-23 20:25:25.202651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bbc40d15f7'
down_revision = 'c06f656a02ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.add_column('bank_account', sa.Column('plaid_account_id', sa.String(length=255), nullable=True))
    op.add_column('bank_account', sa.Column('available_balance', sa.Float(), nullable=True))
    op.add_column('bank_account', sa.Column('current_balance', sa.Float(), nullable=True))
    op.add_column('bank_account', sa.Column('currency_code', sa.String(length=10), nullable=True))
    op.create_unique_constraint(None, 'bank_account', ['plaid_account_id'])
    op.add_column('plaid_item', sa.Column('available_balance', sa.Float(), nullable=True))
    op.add_column('plaid_item', sa.Column('current_balance', sa.Float(), nullable=True))
    op.add_column('plaid_item', sa.Column('iso_currency_code', sa.String(length=10), nullable=True))
    op.add_column('plaid_item', sa.Column('limit', sa.Float(), nullable=True))
    op.add_column('plaid_item', sa.Column('unofficial_currency_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plaid_item', 'unofficial_currency_code')
    op.drop_column('plaid_item', 'limit')
    op.drop_column('plaid_item', 'iso_currency_code')
    op.drop_column('plaid_item', 'current_balance')
    op.drop_column('plaid_item', 'available_balance')
    op.drop_constraint(None, 'bank_account', type_='unique')
    op.drop_column('bank_account', 'currency_code')
    op.drop_column('bank_account', 'current_balance')
    op.drop_column('bank_account', 'available_balance')
    op.drop_column('bank_account', 'plaid_account_id')
    op.create_table('account',
    sa.Column('account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mask', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('official_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('subtype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('available_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('current_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('iso_currency_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('limit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('unofficial_currency_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], name='account_user_id_fkey'),
    sa.PrimaryKeyConstraint('account_id', name='account_pkey')
    )
    # ### end Alembic commands ###
