"""empty message

Revision ID: 64cf265779b1
Revises: 7b4cd4f99401
Create Date: 2023-08-23 16:54:30.960749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64cf265779b1'
down_revision = '7b4cd4f99401'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('ticker_symbol', sa.String(length=50), nullable=True),
    sa.Column('iso_currency_code', sa.String(length=10), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('close_price_as_of', sa.Date(), nullable=True),
    sa.Column('unofficial_currency_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_security')
    # ### end Alembic commands ###
