"""empty message

Revision ID: 658816af5432
Revises: 55bbc40d15f7
Create Date: 2023-09-02 17:10:09.317927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658816af5432'
down_revision = '55bbc40d15f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_holding', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('investment_holding', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('investment_holding', sa.Column('ticker_symbol', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'investment_holding', 'investment_security', ['security_id'], ['security_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'investment_holding', type_='foreignkey')
    op.drop_column('investment_holding', 'ticker_symbol')
    op.drop_column('investment_holding', 'type')
    op.drop_column('investment_holding', 'name')
    # ### end Alembic commands ###
