"""empty message

Revision ID: 6e2b85116e69
Revises: d2f75b1112f4
Create Date: 2023-09-19 12:57:44.804256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e2b85116e69'
down_revision = 'd2f75b1112f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('subscription_end_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'subscription_end_date')
    # ### end Alembic commands ###
