"""empty message

Revision ID: 77b576c21a49
Revises: 9bffc8e29d1c
Create Date: 2023-09-02 22:45:33.321755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77b576c21a49'
down_revision = '9bffc8e29d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('security_id', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('institution_price', sa.Float(), nullable=True),
    sa.Column('institution_price_currency', sa.String(length=10), nullable=True),
    sa.Column('institution_value', sa.Float(), nullable=True),
    sa.Column('institution_value_currency', sa.String(length=10), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('ticker_symbol', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('account_mask', sa.String(length=255), nullable=True),
    sa.Column('account_subtype', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_view')
    # ### end Alembic commands ###
