"""empty message

Revision ID: 78df83d4d3e7
Revises: 658816af5432
Create Date: 2023-09-02 21:08:23.011883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78df83d4d3e7'
down_revision = '658816af5432'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('account_id', sa.String(length=255), nullable=True),
    sa.Column('security_id', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('institution_price', sa.Float(), nullable=True),
    sa.Column('institution_price_currency', sa.String(length=10), nullable=True),
    sa.Column('institution_value', sa.Float(), nullable=True),
    sa.Column('institution_value_currency', sa.String(length=10), nullable=True),
    sa.Column('cost_basis', sa.Float(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('ticker_symbol', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=255), nullable=True),
    sa.Column('account_mask', sa.String(length=255), nullable=True),
    sa.Column('account_subtype', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('investment_holding', 'ticker_symbol')
    op.drop_column('investment_holding', 'type')
    op.drop_column('investment_holding', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investment_holding', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('investment_holding', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('investment_holding', sa.Column('ticker_symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_table('investment_view')
    # ### end Alembic commands ###
