"""empty message

Revision ID: 7b1df4780655
Revises: bba98ab2a66f
Create Date: 2023-10-03 11:25:54.558982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1df4780655'
down_revision = 'bba98ab2a66f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('marital_status', sa.String(length=50), nullable=True))
    op.add_column('customer', sa.Column('dependents', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('employment_status', sa.String(length=50), nullable=True))
    op.add_column('customer', sa.Column('annual_income', sa.Float(), nullable=True))
    op.add_column('customer', sa.Column('income_source', sa.String(length=255), nullable=True))
    op.add_column('customer', sa.Column('major_expenses_next_5_years', sa.String(length=255), nullable=True))
    op.add_column('customer', sa.Column('financial_commitments', sa.Text(), nullable=True))
    op.add_column('customer', sa.Column('college_dependents_next_10_years', sa.Boolean(), nullable=True))
    op.add_column('customer', sa.Column('investment_duration', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('investment_knowledge_rating', sa.Integer(), nullable=True))
    op.add_column('customer', sa.Column('investment_reaction', sa.String(length=50), nullable=True))
    op.add_column('customer', sa.Column('capital_preference', sa.String(length=50), nullable=True))
    op.add_column('customer', sa.Column('debt_feeling', sa.String(length=50), nullable=True))
    op.add_column('customer', sa.Column('anticipated_changes_next_3_5_years', sa.Boolean(), nullable=True))
    op.add_column('customer', sa.Column('review_frequency', sa.String(length=50), nullable=True))
    op.drop_column('customer', 'life_stage')
    op.drop_column('customer', 'risk_tolerance')
    op.drop_column('customer', 'onboarding_complete')
    op.drop_column('customer', 'experience_level')
    op.drop_column('customer', 'current_investments')
    op.drop_column('customer', 'financial_goals')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('financial_goals', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('current_investments', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('experience_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('onboarding_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('risk_tolerance', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('customer', sa.Column('life_stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('customer', 'review_frequency')
    op.drop_column('customer', 'anticipated_changes_next_3_5_years')
    op.drop_column('customer', 'debt_feeling')
    op.drop_column('customer', 'capital_preference')
    op.drop_column('customer', 'investment_reaction')
    op.drop_column('customer', 'investment_knowledge_rating')
    op.drop_column('customer', 'investment_duration')
    op.drop_column('customer', 'college_dependents_next_10_years')
    op.drop_column('customer', 'financial_commitments')
    op.drop_column('customer', 'major_expenses_next_5_years')
    op.drop_column('customer', 'income_source')
    op.drop_column('customer', 'annual_income')
    op.drop_column('customer', 'employment_status')
    op.drop_column('customer', 'dependents')
    op.drop_column('customer', 'marital_status')
    op.drop_column('customer', 'age')
    # ### end Alembic commands ###
