"""empty message

Revision ID: 98371b6f65e9
Revises: f9ca2b67bfb8
Create Date: 2023-09-19 19:21:28.791706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98371b6f65e9'
down_revision = 'f9ca2b67bfb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bank_account_plaid_access_token_key', 'bank_account', type_='unique')
    op.drop_column('bank_account', 'plaid_access_token')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('plaid_access_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint('bank_account_plaid_access_token_key', 'bank_account', ['plaid_access_token'])
    # ### end Alembic commands ###
