"""empty message

Revision ID: 9bffc8e29d1c
Revises: 78df83d4d3e7
Create Date: 2023-09-02 22:12:46.862131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bffc8e29d1c'
down_revision = '78df83d4d3e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investment_view')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_view',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('security_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('institution_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('institution_price_currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('institution_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('institution_value_currency', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('cost_basis', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ticker_symbol', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('account_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('account_mask', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('account_subtype', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], name='investment_view_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='investment_view_pkey')
    )
    # ### end Alembic commands ###
