"""empty message

Revision ID: bba98ab2a66f
Revises: 4541c837ea58
Create Date: 2023-09-30 14:33:53.547275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bba98ab2a66f'
down_revision = '4541c837ea58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('onboarding_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'onboarding_complete')
    # ### end Alembic commands ###
