"""Added onboarding_complete to Customer

Revision ID: bdf9efc60923
Revises: 14936d270ed1
Create Date: 2023-10-13 17:11:32.374099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdf9efc60923'
down_revision = '14936d270ed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('onboarding_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'onboarding_complete')
    # ### end Alembic commands ###
