"""added InvestmentTransaction and more columns to investment tables

Revision ID: bf795a489842
Revises: 405f57239599
Create Date: 2023-08-21 20:41:17.274675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf795a489842'
down_revision = '405f57239599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_security',
    sa.Column('security_id', sa.String(length=255), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('close_price_as_of', sa.Date(), nullable=True),
    sa.Column('cusip', sa.String(length=255), nullable=True),
    sa.Column('isin', sa.String(length=255), nullable=True),
    sa.Column('iso_currency_code', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('ticker_symbol', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('unofficial_currency_code', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('security_id')
    )
    op.add_column('investment_holding', sa.Column('institution_price', sa.Float(), nullable=True))
    op.add_column('investment_holding', sa.Column('institution_price_currency', sa.String(length=10), nullable=True))
    op.add_column('investment_holding', sa.Column('institution_value', sa.Float(), nullable=True))
    op.add_column('investment_holding', sa.Column('institution_value_currency', sa.String(length=10), nullable=True))
    op.add_column('investment_holding', sa.Column('cost_basis', sa.Float(), nullable=True))
    op.add_column('investment_holding', sa.Column('cost_basis_currency', sa.String(length=10), nullable=True))
    op.add_column('investment_holding', sa.Column('iso_currency_code', sa.String(length=10), nullable=True))
    op.add_column('investment_holding', sa.Column('unofficial_currency_code', sa.String(length=10), nullable=True))
    op.add_column('investment_transaction', sa.Column('transaction_id', sa.String(length=255), nullable=False))
    op.add_column('investment_transaction', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('investment_transaction', sa.Column('quantity', sa.Float(), nullable=True))
    op.add_column('investment_transaction', sa.Column('institution_value', sa.Float(), nullable=True))
    op.add_column('investment_transaction', sa.Column('institution_value_currency', sa.String(length=10), nullable=True))
    op.add_column('investment_transaction', sa.Column('subtype', sa.String(length=50), nullable=True))
    op.add_column('investment_transaction', sa.Column('cancel_transaction_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_transaction', 'cancel_transaction_id')
    op.drop_column('investment_transaction', 'subtype')
    op.drop_column('investment_transaction', 'institution_value_currency')
    op.drop_column('investment_transaction', 'institution_value')
    op.drop_column('investment_transaction', 'quantity')
    op.drop_column('investment_transaction', 'name')
    op.drop_column('investment_transaction', 'transaction_id')
    op.drop_column('investment_holding', 'unofficial_currency_code')
    op.drop_column('investment_holding', 'iso_currency_code')
    op.drop_column('investment_holding', 'cost_basis_currency')
    op.drop_column('investment_holding', 'cost_basis')
    op.drop_column('investment_holding', 'institution_value_currency')
    op.drop_column('investment_holding', 'institution_value')
    op.drop_column('investment_holding', 'institution_price_currency')
    op.drop_column('investment_holding', 'institution_price')
    op.drop_table('investment_security')
    # ### end Alembic commands ###
