"""empty message

Revision ID: c0af797cbf0e
Revises: 1680a6eee987
Create Date: 2023-08-22 20:05:30.080408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0af797cbf0e'
down_revision = '1680a6eee987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mask', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('official_name', sa.String(length=255), nullable=True),
    sa.Column('subtype', sa.String(length=255), nullable=True),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('available_balance', sa.Float(), nullable=True),
    sa.Column('current_balance', sa.Float(), nullable=True),
    sa.Column('iso_currency_code', sa.String(length=10), nullable=True),
    sa.Column('limit', sa.Float(), nullable=True),
    sa.Column('unofficial_currency_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.drop_column('investment_holding', 'unofficial_currency_code')
    op.add_column('investment_security', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('investment_security', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'investment_security', 'customer', ['user_id'], ['id'])
    op.drop_column('investment_security', 'cusip')
    op.drop_column('investment_security', 'isin')
    op.add_column('investment_transaction', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('investment_transaction', sa.Column('unofficial_currency_code', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investment_transaction', 'unofficial_currency_code')
    op.drop_column('investment_transaction', 'type')
    op.add_column('investment_security', sa.Column('isin', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('investment_security', sa.Column('cusip', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'investment_security', type_='foreignkey')
    op.drop_column('investment_security', 'user_id')
    op.drop_column('investment_security', 'id')
    op.add_column('investment_holding', sa.Column('unofficial_currency_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_table('account')
    # ### end Alembic commands ###
