"""empty message

Revision ID: eb6ecbe9c8a4
Revises: 02c5686b5737
Create Date: 2023-10-05 14:12:57.023371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6ecbe9c8a4'
down_revision = '02c5686b5737'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'college_dependents_next_10_years')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('college_dependents_next_10_years', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
