"""empty message

Revision ID: f9ca2b67bfb8
Revises: 208cdb8759ac
Create Date: 2023-09-19 19:20:59.169285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ca2b67bfb8'
down_revision = '208cdb8759ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('account_id', sa.String(length=255), nullable=True))
    op.drop_constraint('bank_account_plaid_account_id_key', 'bank_account', type_='unique')
    op.create_unique_constraint(None, 'bank_account', ['account_id'])
    op.drop_column('bank_account', 'plaid_account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_account', sa.Column('plaid_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bank_account', type_='unique')
    op.create_unique_constraint('bank_account_plaid_account_id_key', 'bank_account', ['plaid_account_id'])
    op.drop_column('bank_account', 'account_id')
    # ### end Alembic commands ###
