"""empty message

Revision ID: fa6ae5621ddb
Revises: 7b1df4780655
Create Date: 2023-10-03 14:55:53.411389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa6ae5621ddb'
down_revision = '7b1df4780655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('investment_profile', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'investment_profile')
    # ### end Alembic commands ###
